version: '3.8'
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: classroombookingdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - classroom-network

  classroom-service:
    image: bibianco/classroom-service:latest
    depends_on:
      - mysql
    ports:
      - "8081:8081"
    networks:
      - classroom-network

  loan-service:
    image: bibianco/loan-service:latest
    depends_on:
      - classroom-service
    ports:
      - "8082:8082"
    networks:
      - classroom-network

  reporting-service:
    image: bibianco/reporting-service:latest
    depends_on:
      - loan-service
    ports:
      - "8083:8083"
    networks:
      - classroom-network

networks:
  classroom-network:

volumes:
  mysql_data:

